# Artificial Neural Network

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf  # usually we would import matplotlib.pyplot, but tensorflow works

In [3]:
tf.__version__  # shows the version of tensorflow that we're using right now

'2.17.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')  # remember we can do this if only the files are in the same directory
# we do not need all the columns
# iloc syntax: df.iloc[row, column]. We want all rows but specific columns here.
x = dataset.iloc[:, 3:-1].values  # iloc stands for integer location, and it is from the pd library
y = dataset.iloc[:, -1].values
# note that iloc index range includes the first integer but excludes the last one, so [:, 3:-1] excludes the last column, which is the "exit" column; [:, -1] includes the "exit" column

In [5]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [7]:
# Label Encoding is changing the categorical data into numerical values, in this case Female might become 1 and male might become 0, or vice versa
from sklearn.preprocessing import LabelEncoder  # a machine learning library
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])  # label encoding will be done to our "Gender" column

In [8]:
print(x)  # the column that we specified to change in the dataset of x will completely be changed (in this case, the "Gender" column)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [9]:
# One Hot Encoding: we use this when the categorical variables don't have relative relations to each other (Spain, Germany, France are not like Female and Male), so it doesn't make sense to use label encoding!
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# to use OneHotEncoder we need to use the ColumnTransformer method too
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')  # we only need to change the index here to [1], bc that's where the countries are located as columns in the LabelEncoded version of the x dataset
x = np.array(ct.fit_transform(x))

In [10]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [11]:
# Import more modules from the sklearn library
# This train_test_split module works to split the dataset into training and test set, just follow the template bellow and I should be good (obv change the variable names if I use this in future models)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [12]:
# Feature scaling is the most important part of training
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

## Part 2 - Building the ANN

### Initializing the ANN

### Adding the input layer and the first hidden layer

### Adding the second hidden layer

### Adding the output layer

## Part 3 - Training the ANN

### Compiling the ANN

### Training the ANN on the Training set

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

### Making the Confusion Matrix